### PR TITLE
Watch js/ts file events and add a simple logging middleware

### PR DESCRIPTION
**Pull request by elephant3**
# Description
2 things are done in this PR:
- nodemon is watching for `*js`, `*.ts` file changes in `functions` folder, including adding of a new file
- a simple logging middleware added (req url, req/res processing time, response status code)

# Notes
Removal of a file still not supported by nodemon, see [here](https://github.com/remy/nodemon/issues/1726)

### CODE REVIEW

**Review by plmercereau — APPROVED** [review]
😎

**Comment by elitan** [comment]
Added a few updates:

- Using [Morgan](https://expressjs.com/en/resources/middleware/morgan.html) for HTTP logging. We should use the same in watchtower.
- Skipping files that should be ignored (file or folder starts with `_`).
- Added `package.json` file so my IDE is happy during development

**Comment by elephant3** [comment]
> We should use the same in watchtower
@elitan could you clarify how do you see that? Include that middleware for functions? But every function is a single route, what's the purpose then?

**Review by elitan — APPROVED** [review]

**Comment by elitan** [comment]
> > We should use the same in watchtower
> 
> @elitan could you clarify how do you see that? Include that middleware for functions? But every function is a single route, what's the purpose then?

To show similar logs for users in the Nhost Dashboard.

**Pull request merged**
